pip install telebot
pip install certifi
pip install charset-normalizer
pip install gcloud
pip install googleapis-common-protos
pip install httplib2
pip install idna
pip install jws
pip install oauth2client
pip install pbr
pip install pip
pip install positional
pip install protobuf
pip install pyasn1
pip install pyasn1-modules
pip install pycryptodome
pip install pyparsing
pip install Pyrebase
pip install requests-toolbelt gcloud oauth2client python-jwt pycryptodome
pip install python-jwt
pip install requests
pip install requests-toolbelt
pip install rsa
pip install setuptools
pip install six
pip install urllib
pip install wheel
pip install wrapt
